/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hcs.healtcaresolution;

import javax.swing.*;

/**
 *
 * @author Sheppard
 */
public class PaginaBenvenuto extends javax.swing.JPanel {

    /**
     * Creates new form PaginaBenvenuto
     */
    public PaginaBenvenuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPannelloBenvenuto = new javax.swing.JPanel();
        bottoneRegistrati = new javax.swing.JButton();
        bottoneAccedi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        testodiBenvenuto = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(102, 102, 102));

        jPannelloBenvenuto.setBackground(new java.awt.Color(102, 102, 102));
        jPannelloBenvenuto.setAlignmentX(0.0F);
        jPannelloBenvenuto.setAlignmentY(0.0F);

        bottoneRegistrati.setBackground(new java.awt.Color(120, 120, 120));
        bottoneRegistrati.setForeground(new java.awt.Color(255, 255, 255));
        bottoneRegistrati.setText("Registrati");

        bottoneAccedi.setBackground(new java.awt.Color(120, 120, 120));
        bottoneAccedi.setForeground(new java.awt.Color(255, 255, 255));
        bottoneAccedi.setText("Accedi");
        bottoneAccedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bottoneAccediMouseClicked(evt);
            }
        });

        jScrollPane2.setBorder(null);

        testodiBenvenuto.setBackground(new java.awt.Color(102, 102, 102));
        testodiBenvenuto.setColumns(20);
        testodiBenvenuto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        testodiBenvenuto.setForeground(new java.awt.Color(255, 255, 255));
        testodiBenvenuto.setRows(5);
        testodiBenvenuto.setText("Benvenuto. Accedi con le credenziali tramite il pulsante Accedi.\nSe non sei registrato puoi farlo tramite l'apposito pulstante.");
        jScrollPane2.setViewportView(testodiBenvenuto);

        javax.swing.GroupLayout jPannelloBenvenutoLayout = new javax.swing.GroupLayout(jPannelloBenvenuto);
        jPannelloBenvenuto.setLayout(jPannelloBenvenutoLayout);
        jPannelloBenvenutoLayout.setHorizontalGroup(
            jPannelloBenvenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannelloBenvenutoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(bottoneAccedi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottoneRegistrati)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelloBenvenutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPannelloBenvenutoLayout.setVerticalGroup(
            jPannelloBenvenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelloBenvenutoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPannelloBenvenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoneRegistrati)
                    .addComponent(bottoneAccedi))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPannelloBenvenuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPannelloBenvenuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneAccediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottoneAccediMouseClicked
        // TODO add your handling code here:
        //pulisco il JFrame
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        
        // Istanza di Home
        Home schermataBenvenuto = new Home();
        frame.getContentPane().add(schermataBenvenuto);
        
        frame.revalidate();
        frame.repaint();
        
    }//GEN-LAST:event_bottoneAccediMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneAccedi;
    private javax.swing.JButton bottoneRegistrati;
    private javax.swing.JPanel jPannelloBenvenuto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea testodiBenvenuto;
    // End of variables declaration//GEN-END:variables
}
