/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hcs.healtcaresolution;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sheppard
 */
public class PannelloConnesso extends javax.swing.JPanel {

    /**
     * Creates new form PannelloConnesso
     */
    public PannelloConnesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jAccesso = new javax.swing.JPanel();
        jBottonePaziente = new javax.swing.JButton();
        jBottoneCareGiver = new javax.swing.JButton();
        jBottoneInfermiere = new javax.swing.JButton();
        jBottoneDottore = new javax.swing.JButton();
        jBottoneIndietro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jAccesso.setBackground(new java.awt.Color(0, 0, 0));

        jBottonePaziente.setBackground(new java.awt.Color(0, 0, 0));
        jBottonePaziente.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jBottonePaziente.setForeground(new java.awt.Color(255, 255, 255));
        jBottonePaziente.setText("Paziente");
        jBottonePaziente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jBottonePaziente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottonePazienteMouseClicked(evt);
            }
        });

        jBottoneCareGiver.setBackground(new java.awt.Color(0, 0, 0));
        jBottoneCareGiver.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jBottoneCareGiver.setForeground(new java.awt.Color(255, 255, 255));
        jBottoneCareGiver.setText("Caregiver");
        jBottoneCareGiver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jBottoneCareGiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottoneCareGiverMouseClicked(evt);
            }
        });

        jBottoneInfermiere.setBackground(new java.awt.Color(0, 0, 0));
        jBottoneInfermiere.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jBottoneInfermiere.setForeground(new java.awt.Color(255, 255, 255));
        jBottoneInfermiere.setText("Infermiere");
        jBottoneInfermiere.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jBottoneInfermiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottoneInfermiereMouseClicked(evt);
            }
        });

        jBottoneDottore.setBackground(new java.awt.Color(0, 0, 0));
        jBottoneDottore.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jBottoneDottore.setForeground(new java.awt.Color(255, 255, 255));
        jBottoneDottore.setText("Medico");
        jBottoneDottore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jBottoneDottore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottoneDottoreMouseClicked(evt);
            }
        });
        jBottoneDottore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBottoneDottoreActionPerformed(evt);
            }
        });

        jBottoneIndietro.setBackground(new java.awt.Color(0, 0, 0));
        jBottoneIndietro.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jBottoneIndietro.setForeground(new java.awt.Color(255, 0, 0));
        jBottoneIndietro.setText("Indietro");
        jBottoneIndietro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBottoneIndietro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBottoneIndietroMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("HEALTH CARE MANAGEMENT\n");

        javax.swing.GroupLayout jAccessoLayout = new javax.swing.GroupLayout(jAccesso);
        jAccesso.setLayout(jAccessoLayout);
        jAccessoLayout.setHorizontalGroup(
            jAccessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAccessoLayout.createSequentialGroup()
                .addGroup(jAccessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAccessoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jAccessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAccessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBottoneCareGiver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBottonePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBottoneDottore, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBottoneInfermiere, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jAccessoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(jAccessoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jBottoneIndietro)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jAccessoLayout.setVerticalGroup(
            jAccessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAccessoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(jBottonePaziente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBottoneDottore, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBottoneCareGiver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBottoneInfermiere, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jBottoneIndietro)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAccesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAccesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jBottoneIndietroMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        
        //Instanza di Registrati
        PaginaBenvenuto regis = new PaginaBenvenuto();
        frame.getContentPane().add(regis);
        
        frame.revalidate();
        frame.repaint();
    }                                             

    private void jBottonePazienteMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        
        //Instanza di Registrati
        PannelloPaziente regis = new PannelloPaziente();
        frame.getContentPane().add(regis);
        
        frame.revalidate();
        frame.repaint();
    }                                             

    private void jBottoneInfermiereMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();

        //Instanza di Registrati
        PannelloPaziente regis = new PannelloPaziente();
        frame.getContentPane().add(regis);

        frame.revalidate();
        frame.repaint();
    }                                               

    private void jBottoneCareGiverMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();

        //Instanza di Registrati
        PannelloPaziente regis = new PannelloPaziente();
        frame.getContentPane().add(regis);

        frame.revalidate();
        frame.repaint();
    }                                              

    private void jBottoneDottoreActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               
                            

    private void jBottoneDottoreMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();

        //Instanza di Registrati
        PannelloPaziente regis = new PannelloPaziente();
        frame.getContentPane().add(regis);

        frame.revalidate();
        frame.repaint();
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JPanel jAccesso;
    private javax.swing.JButton jBottoneCareGiver;
    private javax.swing.JButton jBottoneDottore;
    private javax.swing.JButton jBottoneIndietro;
    private javax.swing.JButton jBottoneInfermiere;
    private javax.swing.JButton jBottonePaziente;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
}
